version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin@2024
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    container_name: postgres
    # volumes:
    #   # - ./pgdata:/var/lib/postgresql/data
    #   - postgres:/var/lib/postgresql/data
    #   # - ./postgresql/conf:/etc/postgresql/
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
      - DB_HOST=localhost
      - DB_PORT= 5432
      - DB_USERNAME= postgres
      - DB_PASSWORD= admin@2024
      - DB_NAME= postgres
      - API_KEY=7d8HMUuVXOWIMlb5PbCy9PkypgNu4SRg
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
# volumes:
#   postgres:
# host.docker.internal
