version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin@2024
  test-db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: admin@2024
